### ISSUE TITLE
Multi thread script run

### ISSUE THREAD

**Issue by antonzol** [tinify/photoshop-scripts#10]
Hello!
Is there a way to use multithread in photoshop script?

For examlpe I have  i5-10400 with 6 cores (12 threads) and PS use only one core (about 14-16% of CPU) ![image](https://user-images.githubusercontent.com/9577962/147668836-c09ad27a-dc06-4a4a-a730-185e3b9497c6.png)

**Comment by rolftimmermans** [comment]
To my knowledge Photoshop does not support this, but to be sure it's better to contact Adobe about this.

With regards to the image optimisation, this is inherently difficult to parallelise in most cases, because most optimisations are by nature an operation on the entire image and not on their parts.
