### ISSUE TITLE
Renaming tinyPng file

### ISSUE THREAD

**Issue by artmelkon** [tinify/photoshop-scripts#4]
Hello,
I was wondering if there is a way to rename the file by running the script.
Thanks

**Comment by mattijsvandruenen** [comment]
Hi,

You could make a small modification to the script to save the compressed file with a different filename.
Instead of `tinify.putPath(charIDToTypeID("In  "), file);` you could use something like
```
var compressedFile = new File("/path/to/the/folder/" + file.name.replace(".jpg", "-compressed.jpg"));
tinify.putPath(charIDToTypeID("In  "), compressedFile);
```
For example, if you would compress a file called `test.jpg` this change would save the compressed result as `test-compressed.jpg`

Make sure you use the full path of the new to be created file, otherwise it will not work.

I hope that helps you on your way!

**Comment by artmelkon** [comment]
It works like a charm, thank you so much.
